const MSG = {
  AUTH: {
    PASSWORD_NOT_MATCH: 'PASSWORD AND CONFIRM PASSWORD IS NOT MATCH',
    USER_PASSWORD_INVALID: 'USERNAME OR PASSWORD IS INVALID'
  },
  DISTANCE_MATRIX: {
    ZERO_RESULT_MATRIX: `ZERO_RESULTS`,
    NOT_FOUND_MATRIX: `NOT_FOUND`
  },
  RESTAURANT: {
    NOT_FOUND: 'NOT FOUND RESTAURANT'
  },
  RESERVE_TABLE: {
    EVIDENCE: 'PLEASE ATTACH THE PAYMENT EVIDENCE',
    NOT_FOUND_HISTORY: 'NOT FOUND BOOKING HISTORY'
  }
}

export { MSG }
