const TRAVEL_MODE = {
    DRIVING: "DRIVING",
    TRANSIT: "TRANSIT",
    BICYCLING: "BICYCLING",
    WALKING: "WALKING"
}
const LANGUAGE = {
    TH: "TH",
    EN: "EN"
}
const DESTINATION_UNIT = {
    METRIC: "METRIC",
    IMPERIAL: "IMPERIAL"
}
const LIMIT_DESTINATION = 25
const NEAREST_DISTANCE = 50
const DISTANCE_MATRIX_ERROR_MSG = ["ZERO_RESULTS", "NOT_FOUND"]

export {
    TRAVEL_MODE,
    LANGUAGE,
    DESTINATION_UNIT,
    LIMIT_DESTINATION,
    NEAREST_DISTANCE,
    DISTANCE_MATRIX_ERROR_MSG
}
