const RESTAURANT_TYPE = {
    FAST_FOOD: "FAST_FOOD",
    CASUAL: "CASUAL",
    FINE_DINING: "FINE_DINING",
    DELIVERY: "DELIVERY",
    BUFFET: "BUFFET",
    A_LA_CARTE: "A_LA_CARTE",
}

const POSITION = {
    HEAD_CHEF: "HEAD_CHEF",
    ASSISTANT_CHEF: "ASSISTANT_CHEF",
    KITCHEN_STAFF: "KITCHEN_STAFF",
    KITCHEN_CLEANING_STAFF: "KITCHEN_CLEANING_STAFF",
    STORE_MANAGER: "STORE_MANAGER",
    RECEPTIONIST: "RECEPTIONIST",
    CASHIER: "CASHIER",
    WAITER: "WAITER",
}

const SERVICE = {
    RESERVE_A_TABLE: "RESERVE_A_TABLE",
    ORDER_FOOD: "ORDER_FOOD",
    BEST_SELLER: "BEST_SELLER",
    REVIEW: "REVIEW"
}

const BOOKING_METHOD = {
    ONLINE: "ONLINE",
    WALK_IN: "WALK_IN"
}

const TABLE_SIZE = {
    S: "S",
    M: "M",
    L: "L",
    XL: "XL",
}

export {
    RESTAURANT_TYPE,
    POSITION,
    SERVICE,
    BOOKING_METHOD,
    TABLE_SIZE
}