const USER_SPREAD_SHEET_ID = '1aQSSEynNV4jho33GdgGKdUlCWp_ej9uPNjPljXdFX5c'
const SHEET_NAME = {
  USER: 'user',
  BOOKING: 'booking'
}
const VALUE_INPUT_OPTION = {
  RAW: 'RAW',
  USER_ENTERED: 'USER_ENTERED'
}
export { USER_SPREAD_SHEET_ID, SHEET_NAME,VALUE_INPUT_OPTION }
