const ROLES = {
    RESTAURANT: "RESTAURANT",
    PUB_BAR: "PUB_BAR",
    HOSPITAL: "HOSPITAL",
    GAS_STATION: "GAS_STATION", 
    GARAGE: "GARAGE", 
    NORMAL_USER: "NORMAL_USER", 
}

export {
    ROLES
}